use_frameworks!

platform :ios, '8.0'

target 'AXX_HomeWorkBLib_Example' do
  pod 'AXX_HomeWorkBLib', :path => '../'

  target 'AXX_HomeWorkBLib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
